pipeline:
  name: SamplePipeline
  identifier: SamplePipeline
  projectIdentifier: TestProj
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.SampleGITHUB
        build: <+input>
  stages:
    - stage:
        name: "build test and run "
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.LocalCluster_
              namespace: harness
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:1.15
                    shell: Sh
                    command: echo "welcome to CI"
